import Config from 'react-native-config';

export const isProd = Config.ENV === 'prd';
export const baseURL = Config.BASE_URL;

export const api = {
  login: 'auth/local/signin',
  signup: 'auth/local/signup',
  editProfile: 'profile/edit',
  createProfile: 'profile/create',
  profiledetails: 'profile',
  requestPassword: 'auth/request-reset-password',
  resetPassword: 'auth/reset-password',
  logout: 'auth/logout',
  changepassword: 'auth/change-password',
  refreshToken: 'auth/refresh',
  createPhoto: 'photo/create',
  getMyphotos: 'photo/my-photos',
  getAlbumphotos: 'photo/album-photos/',
  getMyTripPhotos: 'photo/trip-photos',
  sendPhoto: 'photo/send-photo',
  confirmAllPhotos: 'photo/confirm-all-photos-uploaded/',
  getAlbumConfirmedStatus: 'photo/is-photo-album-upload-confirmed/',
  getSignedUrlPhotos: 'photo/upload-urls-images',
  editNotes: 'notes/',
  getNotes: 'notes/',
  deleteNotes: 'notes/',
  addNotes: 'notes/',
  passengersList: 'passengers-list',
  passengersListBirthday: 'passengers-list/birthday',
  clientUpdateImageProfile: 'passengers-list/update-profile',
  reservationGroupPaxList: 'passengers-list/reservation-group',
  singlePax: 'single-pax/',
  faq: 'faq/',
  roomList: 'room-list/',
  guidePlan: 'guideplan/',
  getItinerary: 'itinerary/',
  emergencyContact: 'emergency-contact/',
  moreInformation: 'more-info/',
  vsocialProjects: 'more-info/vsocial-projects',
  getTripSummary: 'itinerary/trip-summary',
  destinations: 'itinerary/destinations',
  flightReachability: 'flight/reachability',
  flightInformation: 'flight/flight-information',
  flightInformationPax: 'flight/flight-information/pax',
  chat: 'chat',
  sendImage: 'message/upload-media',
  updateDepartureId: 'profile/updateDeparture/',
  recommendedRestaurants: 'restaurants',
};
